### ISSUE TITLE
optional Array validate error

### ISSUE THREAD

**Issue by u2** [intridea/grape#929]
when
```
            params do
              optional :photos, type: Array do
                optional :id, type: Integer
                optional :photo_path, type: String
                optional :width, type: Integer
                optional :height, type: Integer
                optional :description, type: String, default: ''
              end

              optional :videos, type: Array do
                optional :id, type: Integer
                optional :video_path, type: String
                optional :width, type: Integer
                optional :height, type: Integer
                optional :description, type: String, default: ''
                optional :persistent_id, type: String
              end
            end

            post '/array' do
            end
```
The params like below:
```
parameters: {"vedios"=>[nil], "photos"=>[nil]}
```

It return the error:
```
NoMethodError (undefined method `[]' for nil:NilClass):
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/validations/validators/default.rb:17:in `block in validate!'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/validations/attributes_iterator.rb:15:in `block (2 levels) in each'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/validations/attributes_iterator.rb:14:in `each'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/validations/attributes_iterator.rb:14:in `block in each'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/validations/attributes_iterator.rb:13:in `each'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/validations/attributes_iterator.rb:13:in `each'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/validations/validators/default.rb:16:in `validate!'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/endpoint.rb:235:in `block in run'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/endpoint.rb:233:in `each'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/endpoint.rb:233:in `run'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/endpoint.rb:195:in `block in call!'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic-grape-2.0.0/lib/newrelic-grape/instrument.rb:21:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic-grape-2.0.0/lib/newrelic-grape/instrument.rb:21:in `block in call!'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:365:in `perform_action_with_newrelic_trace'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic-grape-2.0.0/lib/newrelic-grape/instrument.rb:20:in `call!'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/middleware/base.rb:18:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/middleware/base.rb:24:in `call!'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/middleware/base.rb:18:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/middleware/base.rb:24:in `call!'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/middleware/base.rb:18:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/middleware/error.rb:27:in `block in call!'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/middleware/error.rb:26:in `catch'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/middleware/error.rb:26:in `call!'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/middleware/base.rb:18:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/endpoint.rb:196:in `call!'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/endpoint.rb:184:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:152:in `block in call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:96:in `block in recognize'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:96:in `optimized_each'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:95:in `recognize'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:141:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/api.rb:98:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/api.rb:33:in `call!'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/api.rb:29:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/journey/router.rb:71:in `block in call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/journey/router.rb:59:in `each'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/journey/router.rb:59:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/routing/route_set.rb:678:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/rack/agent_hooks.rb:26:in `traced_call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/rack/developer_mode.rb:56:in `traced_call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/meta_request-0.3.4/lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/meta_request-0.3.4/lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/conditionalget.rb:35:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/remotipart-1.2.1/lib/remotipart/middleware.rb:27:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/middleware/flash.rb:254:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/query_cache.rb:36:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:82:in `run_callbacks'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/middleware/reloader.rb:73:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/better_errors-2.0.0/lib/better_errors/middleware.rb:84:in `protected_app_call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/better_errors-2.0.0/lib/better_errors/middleware.rb:79:in `better_errors_call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/better_errors-2.0.0/lib/better_errors/middleware.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-contrib-1.2.0/lib/rack/contrib/response_headers.rb:17:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/meta_request-0.3.4/lib/meta_request/middlewares/headers.rb:16:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/rack/logger.rb:38:in `call_app'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/rack/logger.rb:20:in `block in call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/tagged_logging.rb:26:in `tagged'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.5/lib/active_support/tagged_logging.rb:68:in `tagged'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/rack/logger.rb:20:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/quiet_assets-1.0.3/lib/quiet_assets.rb:23:in `call_with_quiet_assets'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/actionpack-4.1.5/lib/action_dispatch/middleware/static.rb:64:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/engine.rb:514:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/application.rb:144:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/railtie.rb:194:in `public_send'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/railtie.rb:194:in `method_missing'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-cors-0.2.9/lib/rack/cors.rb:54:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/thin-1.6.3/lib/thin/connection.rb:53:in `process'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/faye-websocket-0.8.0/lib/faye/adapters/thin.rb:40:in `process'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/faye-websocket-0.8.0/lib/faye/adapters/thin.rb:44:in `receive_data'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/handler/thin.rb:16:in `run'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/server.rb:264:in `start'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/commands/server.rb:69:in `start'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:81:in `block in server'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:76:in `tap'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:76:in `server'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.5/lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:4:in `require'
  bin/rails:4:in `<main>'
```

**Comment by dm1try** [comment]
The params looks strange for me. Do you wanna send array with one `nil` element?(or you wanna send just empty array?)

Anyway grape must return validation error and do not throw `NoMethodError`. It is a bug.

**Comment by u2** [comment]
It's just a empty array.
This `parameters: {"vedios"=>[nil], "photos"=>[nil]}` is the grape log.

**Comment by u2** [comment]
This issue and #928 can be closed I think.

**Comment by dblock** [comment]
Fixed.
