### ISSUE TITLE
NoMethodError (undefined method `merge'

### ISSUE THREAD

**Issue by u2** [intridea/grape#954]
This is my grape code:
```
         get do
            entry = Entry.includes(:entry_items).find(params[:id])
            present entry, with: Entities::Entry::Entry, cids: params[:cids]

            entry_user = EntryUser.where(current_user.id).where(entry_id: entry.id).first if current_user
            present entry_user, Entities::Entry::DetailEntryUser if entry_user

            present ApiMeta.new, with: Entities::Meta::Base
          end
```
my entities is like below:
```
        class Entry < Grape::Entity
          root 'entries', 'entry'

          expose :id, :quota, :cover, :title, :date_desc, :sponsor, :latitude, :longitude, :address, :instruction, :total_user_count, :community_city_id, :community_group_id, :state
          expose :share_title, :share_desc, :share_desc2, :share_url, :share_icon

          expose :entry_items, using: EntryItem
        end

        class EntryForm < Grape::Entity
          root 'entries', 'entry'
          expose :id, :title, :date_desc, :cover, :state, :community_group_id
        end

        class EntryUser < Grape::Entity
          root 'entry_users', 'entry_user'
          expose :id, :code, :community_thread_id
        end

        class DetailEntryUser < EntryUser
          root 'entry_users', 'entry_user'
          expose :entry, using: EntryForm
        end
````
but grape give a error:
```
NoMethodError (undefined method `merge' for #<EntryUser:0x007f97b7ba8910>):
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/activemodel-4.1.5/lib/active_model/attribute_methods.rb:435:in `method_missing'
  /Users/u2/.rvm/gems/ruby-2.1.2/gems/activerecord-4.1.5/lib/active_record/attribute_methods.rb:208:in `method_missing'
  /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/grape-81c986ac7aca/lib/grape/dsl/inside_route.rb:200:in `present'
  /Users/u2/weddingServer/app/api/v1/app/entries.rb:32:in `block (3 levels) in <class:Entries>'
```
My colleague and I check the code again and again,but did not find the problem.And we have used `grape-entity` for a long time.It's a little weird.

**Comment by u2** [comment]
Sorry, I find the problem, we forget  `with`:
```
 present entry_user, Entities::Entry::DetailEntryUser if entry_user
```
It's a little shamed.

**Comment by dblock** [comment]
I wonder whether we want a specialized error that says `missing :with` or something like that? I'll close, but feel free to PR something to that effect.
